# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Uganda Parliament Watch
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results).
baseurl: "/uganda-parliament-watch" # the subpath of your site, e.g. /blog
url: "https://theyworkforyou.github.io" # the base hostname & protocol for your site
twitter_username:
exclude: [Gemfile, Gemfile.lock, README.md, vendor]

# Build settings
markdown: kramdown

everypolitician:
  sources:
    - https://github.com/everypolitician/everypolitician-data/raw/uganda-spreadsheet/data/Uganda/Parliament/ep-popolo-v1.0.json

collections:
  people:
    output: true
    permalink: '/mp/:path/'
  events:
    output: true
    permalink: '/term/:path/'
